export const desserts = [
    {
        image: 'assets/images/image-waffle-desktop.jpg',
        alt: 'image of waffles',
        category: 'Waffle',
        name: 'Waffle with Berries',
        price: '6.50',
    },
    {
        image: 'assets/images/image-creme-brulee-desktop.jpg',
        alt: 'image of creme brulee',
        category: 'Crème Brûlée',
        name: 'Vanilla Bean Crème Brûlée',
        price: '7.00',
    },
    {
        image: 'assets/images/image-macaron-desktop.jpg',
        alt: 'image of macaron',
        category: 'Macaron',
        name: 'Macaron Mix of Five',
        price: '8.00',
    },
    {
        image: 'assets/images/image-tiramisu-desktop.jpg',
        alt: 'image of tiramisu',
        category: 'Tiramisu',
        name: 'Classic Tiramisu',
        price: '5.50',
    },
    {
        image: 'assets/images/image-baklava-desktop.jpg',
        alt: 'image of baklava',
        category: 'Baklava',
        name: 'Pistachio Baklava',
        price: '4.00',
    },
    {
        image: 'assets/images/image-meringue-desktop.jpg',
        alt: 'image of waffles',
        category: 'Pie',
        name: 'Lemon Meringue Pie',
        price: '5.00',
    },
    {
        image: 'assets/images/image-cake-desktop.jpg',
        alt: 'image of waffles',
        category: 'Cake',
        name: 'Red Velvet Cake',
        price: '4.50',
    },
    {
        image: 'assets/images/image-brownie-desktop.jpg',
        alt: 'image of waffles',
        category: 'Brownie',
        name: 'Salted Caramel Brownie',
        price: '4.50',
    },
    {
        image: 'assets/images/image-panna-cotta-desktop.jpg',
        alt: 'image of waffles',
        category: 'Panna Cotta',
        name: 'Vanilla Panna Cotta',
        price: '6.50',
    },
]